### ISSUE TITLE
Does upgradeChaincode.js work?

### ISSUE THREAD

**Issue by a037580238** [wearetheledger/fabric-network-boilerplate#7]
Excuse me. I have question about upgrade chaincode with nodejs sdk.
1. I have used upgradeChaincode.js but error happened.
import { init, query } from './hlfClient';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

I have search the problem. And try to fix it.
But it seems import, some ES6 and typescript syntax can't work in frontend.

2. Can other features work with nodejs sdk?
create-channel
join-channel
install-chaincode
instantiate-chaincode

Thanks.

**Comment by Superjo149** [comment]
1. This does not, I didn't finish implementing this, I rewrote this into a .sh script now. I'll push it when I add some other small improvements. 
2. Yes, these features all work using the nodejs sdk.
